README.md
=> add Default Ignore modules setion to README.md

.editorconfig, .eslintrc, package.json
=> Improve .eslintrc

README.md, package.json
=> making npm scripts cross-platform, and add notice to readme

README.md, package.js, package.json
=> --all option

app/containers/AboutPageContainer.jsx, app/containers/HomePageContainer.jsx
=> fix #24, fix defaultProps typo

app/dispatcher/AppDispatcher.js
two imports in AppDispatcher.js are incorrect
=> fix dispatcher imports

README.md
This should save some time for those who follow readme.
=> a little bit more clear docs

package.json
@chentsulin I think this is what we discussed as a fix for #57. If not let me know and I can tweak it.
=> Set NODE_ENV to production for package, build targets

README.md
=> Add React Transform HMR link #60

package.js
=> Add prune to electron-packager opts

.travis.yml
refer: http://docs.travis-ci.com/user/migrating-from-legacy
=> Upgrade Travis from legacy to container-based infrastructure

package.js, package.json
=> Windows patch

package.json
=> Upgrade history and react-router

.travis.yml, test/e2e.js
related https://github.com/chentsulin/electron-react-boilerplate/pull/113#issuecomment-167597333
=> Delay webdriver build (wait chromedriver start time)

test/e2e.js
Extend the timeout for each test
=> Add global timeout to E2E test

.travis.yml, app/containers/App.js, app/reducers/counter.js, package.js, test/components/Counter.spec.js, test/containers/CounterPage.spec.js, test/e2e.js
1. Fix 13 lint errors
2. Add lint task to Travis
=> Fix lint errors

webpack.config.development.js
=> Enable CSS source maps

package.json
=> Use cross-env instead of better-npm-run

app/store/configureStore.development.js, app/store/configureStore.production.js, package.json
http://rackt.org/redux/docs/api/createStore.html
=> Update redux to v3.2.1 and API usage

package.json, webpack.config.base.js
Related to discussion of #128.
=> Add json-loader

README.md
Awesome project! Just saw a little typo and thought I'd open a quick PR.
=> Typo in README.md: form -> from

package.json
Related to https://github.com/babel/babel-eslint/issues/267.
=> Set ESLint version to ~2.2.0

main.development.js
Related to #223.
Should use `mainWindow.webContents.reload()`.
=> Fix Reload menu item click

server.js
If you run `npm run dev`, and then close app with `cmd+q`, dev server is still opened.
=> Fix not stopping dev server on sigterm.

webpack.config.production.js
See: https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin
=> Fix typo: `OccurenceOrderPlugin` to `OccurrenceOrderPlugin`

app/app.html, server.js, webpack.config.development.js
Fixes https://github.com/chentsulin/electron-react-boilerplate/issues/308
=> Dev server port customization

app/app.html
Obviously up to you if you want to merge this. A neat side effect of block-scoping with `const` and `let` is that you don't need [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression)s.
=> Remove IIFEs from app.html.

package.js
=> Fix: replace electron-prebuilt to electron

README.md
This is outdated. To me it seems like it should be removed.
=> Removed outdated readme information

package.json
HMR not working on Windows and it took me like 40 minutes to figure it out. I verified this was the cause before sending this PR.
=> Making HMR to work on Windows

.eslintrc, app/app.global.css, app/store/configureStore.development.js, package.js, server.js, webpack.config.base.js, webpack.config.development.js, webpack.config.electron.js, webpack.config.production.js, webpack.config.test.js
Hi.
First and foremost thank you for work you have done on this. I'm coming from an app where we use a lot of tooling around React and Redux, but a lot of this was black magic to me (hot reloading and some test cases especially).
That said, to understand it I've gone through the project and commented non-obvious parts around the build setup with quick description and links to further details + fixed few code style bits + removed tools dir where there was only a stale submodule.
This is first of all helpful to me and potentially for my team, however it may be useful to other newcomers as well.
If you'll find it useful, but find some glitches or things that are not true, I'm ready to clean it up.
=> Comments and cleanup

app/app.html
it looks #440 reverted some of the things changed. 😂
=> Fix port for app.html

README.md, setup.js
There has been some confusion as to the point of `setup.js` and what it means. This PR is aimed to clarify this as well as reduce confusion.
This is in response to issue #506
=> Create documentation around the cleanup script

README.md, app/package.json, webpack.config.base.js, webpack.config.electron.js
Related to https://github.com/chentsulin/electron-react-boilerplate/issues/524#issuecomment-259461545.
=> Use dependencies of `app/package.json` as webpack externals

webpack.config.production.js
Reverts chentsulin/electron-react-boilerplate#558
=> Revert "Adapt publicPath in webpack.config.production.js"

app/app.html
**DONT MERGE. NEEDS TESTING**
Inspired by https://github.com/chentsulin/electron-react-boilerplate/issues/423#issuecomment-265875725
=> Fix #423, Dynamic Script Injection Warning

package.json, setup.js
I've updated `boiler-room-custodian` (current version is 0.6.1) to handle this scenario. I then modified `setup.js` to exercise the new brc functionality and to resolve #664.
=> add proper cleanup for store config

package.json
Reverts chentsulin/electron-react-boilerplate#670
=> Revert "Update babili-webpack-plugin to version 0.0.8 🚀"

package.json, test/e2e.js, webpack.config.electron.js, webpack.config.production.js, yarn.lock
Related to #672. Disable `deadcode` minify until upstream issue fixed.
I'm push test case first, let we see CI logs.
=> Disable deadcode minify until upstream issue fixed

webpack.config.development.js
=> Add image loaders to development env config.

app/menu.js
=> Fix `Inspect element` of context menu

app/store/configureStore.development.js
=> Redux Store Refactor

app/main.development.js, app/menu.js, package.json, webpack.config.base.js, webpack.config.main.prod.js, webpack.config.renderer.dev.dll.js, webpack.config.renderer.dev.js, webpack.config.renderer.prod.js, yarn.lock
Addresses https://github.com/chentsulin/electron-react-boilerplate/issues/891
=> Webpack DLL Config Fix

README.md
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/902
=> Fixed README examples for npm scripts

setup.js
Deleted reference to erb-logo.png file in remove array of boiler-room-custodian setup file because it is not present in the project.
=> Deleted reference to erb-logo.png of setup.js

app/containers/App.js, app/main.development.js, app/routes.js, package.json
Followup https://github.com/chentsulin/electron-react-boilerplate/pull/887#discussion_r110197578
=> Fix npm start and npm run dev

webpack.config.renderer.dev.js
https://github.com/jantimon/html-webpack-plugin/issues/533 Fixes Live reloading loading old content (#909)
=> Fixed HMR (disabled multiStep)

package.json
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/974
=> Updated browserslist electron version

README.md
See discussion here
https://github.com/chentsulin/electron-react-boilerplate/issues/1042#issuecomment-307514773
=> Add more details to the Module Structure

internals/scripts/ElectronRebuild.js
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/1369
=> Fix electron-rebuild script

app/store/configureStore.dev.js
Skip redux logs in console during the tests
=> Skip redux logs in console during the tests

webpack.config.renderer.dev.dll.js, webpack.config.renderer.dev.js, webpack.config.renderer.prod.js
Just modified a regExp to support .sass files.
=> Add .sass files support

app/store/configureStore.prod.js
Addresses the blank page part of #1114.
=> createBrowserHistory to createHashHistory for prod

.travis.yml, app/package.json, appveyor.yml, package.json
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/1723
=> add initial ci publish assets infra

.github/ISSUE_TEMPLATE.md, package.json, yarn.lock
Also needed to update `prettier` for markdown to be properly autofixed.
=> Add node version prompt to issue template

package.json
Closes https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1967
=> fix incorrect path to electron main prod script in yarn start script

README.md
PR's should be made against the next branch so we're going to change the default branch to be next. This will also change the branch people clone from by default so we need to specify that in the instructions so they don't clone next by default
=> Checkout master branch

internals/scripts/CheckYarn.js
[#2044](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2044#issuecomment-448885366)
=> Remove use of chalk during preinstall

README.md
Updated Readme.md with the new OpenCollective sponsor link
=> Updated Readme.md with the new OpenCollective sponsor link

README.md
I have added the Stack Overflow badge as discussed in the issue (fixes #1886).
=> Added the stack-overflow badge on Readme.

.travis.yml
=> Fix travis pipeline #2271

package.json
fixed "start-main-dev": "cross-env HOT=1 , should be START_HOT
Fixes #2282
=> Update package.json, Fixed "start-main-dev": "cross-env HOT=1 , should be START_HOT #2282

app/main.dev.js
=> Added the reopen event when the dock icon is clicked

app/Routes.tsx
=> feat(routets): lazy load routes

internals/scripts/CheckNativeDep.js
- Fix deadlink about two package json structure
- Resolves #2470
=> Fix dead link about two package json

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/1-Bug_report.md, .github/ISSUE_TEMPLATE/2-Feature_request.md
- delete unused template
- fix dead link
=> Update issue template

app/main.dev.ts
Updated `main.dev.ts` file, replaced `require` statements with `import`
Feel free to add something if I miss.
=> Updated man.dev file from require to import

package.json
=> add core-js

.github/workflows/test.yml
=> add jest to github workflow

.github/workflows/test.yml
Fix: Should trigger CI for outside pull requests
=> Add pull_request event to test.yml

app/index.tsx
Fixes #2395.
I believe that this is a proper fix, and not just a workaround. This probably requires validation from someone more knowledgeable.
=> Fix for preload entrypoint

.github/ISSUE_TEMPLATE/1-Bug_report.md, .github/ISSUE_TEMPLATE/2-Question.md, .github/ISSUE_TEMPLATE/3-Feature_request.md
- Add questions template
- Cleaned up bugs template
=> Issue template for questions

.github/workflows/test.yml, yarn.lock
Related: https://github.com/DevExpress/testcafe/issues/4512
=> attempt to fix CI

.erb/configs/webpack.config.renderer.dev.babel.js, .erb/configs/webpack.config.renderer.prod.babel.js
=> fix: Add missing loader for otf fonts

package.json, src/App.global.css, src/App.tsx, src/index.html, src/index.tsx
=> feat: minor improvements

.erb/scripts/CheckNativeDep.js
=> Update CheckNativeDep.js warning

.vscode/settings.json
This PR fixes a leftover from yarn.
=> Fix vscode setting for npm lock files

.github/workflows/publish.yml, .github/workflows/test.yml
Remove the last mensions of yarn in the github config files
=> Chore: Remove last mentions of yarn

.github/stale.yml
Remove enhancement from the exempt list, this is related with electron-react-boilerplate#3048
=> Update Stale Config

.erb/configs/.eslintrc, .erb/configs/webpack.config.renderer.dev.ts, .erb/scripts/check-native-dep.js, .erb/scripts/clean.js, .erb/scripts/electron-rebuild.js, .erb/scripts/link-modules.ts, .erb/scripts/notarize.js, .eslintignore
=> Fix eslint ignoring the .erb directory by default

.erb/configs/webpack.config.renderer.dev.ts, .erb/configs/webpack.config.renderer.prod.ts, assets/assets.d.ts, package-lock.json, package.json
#3307 
- add `@svgr/webpack`
close https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3193 https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2522 https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2015
=> reopen add support of SVG as Component

package-lock.json
#3312 
bump node-abi in electron-rebuild
=> fix node-abi postinstall error

.erb/configs/webpack.config.base.ts, .erb/configs/webpack.config.main.prod.ts, src/main/main.ts, tsconfig.json
Closes https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3324
=> fix: enable sandboxing

package.json
This doesn't hurt anything and is helpful.
=> let electronmon watch everything under src/main

src/main/preload.ts, src/renderer/preload.d.ts
Fix https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3378
=> Better typings for electron handler

package.json
Update @pmmmwh/react-refresh-webpack-plugin
=> chore(@pmmmwh/react-refresh-webpack-plugin)

.erb/configs/webpack.config.renderer.prod.ts
TerserPlugin: Parallel is true by default.
Production. development will be false by default.
=> Updating Production configuration with Correct config

.erb/configs/webpack.config.main.dev.ts, .erb/configs/webpack.paths.ts, .erb/scripts/link-modules.ts, package-lock.json, package.json
It should fix the [issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568) and be compatible with older Electron versions.
Most of the changes have been taken from the issue conversation. (https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-1978225949, https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-1980507893, https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568#issuecomment-2052729272)
@slhck @1111mp @ifree92
=> Fixed issue #3568 - updating electron version and make the app start

package.json
Looks like some info was lost in a recent update, this adds that info back.
=> Fixes to package.json: add "name", update "browserslist"

src/renderer/index.tsx
Fixed Issue when running on web,
TypeError
Cannot read properties of undefined (reading 'ipcRenderer')
=> Fixed TypeError Issue When Running On Web

package.json
Fixes https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3635
=> fix notarize script macos
