package.json

```babel-core``` is required by ```babel-loader``` and its size is ~19 MB.
```node-libs-browser``` is required by ```webpack``` and its size is ~3MB.
If we explicitly define it as dev deps - it won't be copied to the release. As the result, the release will have ~22 MB less size, which is about 20%.

Explicitly declare babel-core and node-libs-browser in devDependencies

---

README.md
package.json

Created a bin link to `./node_modules/.bin/electron`, eliminating the need to have `electron` on your environment, and simultaneously making `scripts` easier to write.

Simplify Electron executable scenario

---

test/e2e.js

The `app=.` is not work on Windows.

Resolve app path of E2E test

---

package.js
package.json

https://github.com/atom/electron/blob/master/docs/api/app.md#appgetname
Electron `app.getName()` default used productName of `package.json`, so we can use it to replace default appName of `package.js`.

Add productName to package.json

---

webpack.config.production.js

Previous value `/dist/` would cause static assets to be searched for in
`file:///dist/...` (root of fs), instead of in the `dist/` directory
relative to `app/index.html`.

Fix Webpack publicPath for production builds

---

package.js

The packaging script now appends a different icon extension depending on the platform:
* win32 needs an .ico
* darwin needs an .icns
* everything else (i.e., linux) needs a png.
This commit assumes an extensionless icon argument, and 3 icon files on disk (like the current script assumes 1) if you're doing a package-all and chooses the correct extension for the platform it's currently being built for.

package script now chooses correct OS icon extension

---

README.md
package.json

Keep open two terminals is bad.
So I added the ability to run two servers with a single command (npm run dev). 
I hope this opportunity will be useful to others.

Added start (hot-server, start-hot) servers with one command

---

package.js

https://github.com/electron-userland/electron-packager has an option `app-version` that should be what the users sets in his package.json. It reverts to the default Electron version if nothing is found.

Version of package is set based on the version in package.json

---

server.js

Hello I don't understand why we need this handler
`app.use(require('webpack-hot-middleware')(compiler));` isn't enough?

Remove unused handler

---

package.js

The `npm run package` is included `npm_config_dev: ""` env, it means it don't check devDependencies.
Related to https://github.com/chentsulin/electron-react-boilerplate/pull/186#issuecomment-201340977.

Fix `npm list electron-prebuilt` in package.js

---

main.js

Open mainWindow when webContents is loaded using the event 'did-finish-load'.
This prevent having a blank window and then content "flash" in.

Open application when webcontent is loaded

---

README.md

Just fixing a type I found in the readme.

fix typo Elecrton in README.md

---

package.js

This was ignoring all folders named `release` in all node_modules
For instance bluebird ships with `js/browser` and `js/release` but `js/release` was ignored during the build process and filtered out.
https://github.com/petkaantonov/bluebird/blob/master/package.json#L71

Fix ignore regex to top level folders

---

main.development.js
package.js
package.json

Removed crashReporter (we don't want to setup a server here to keep the report)
https://github.com/sindresorhus/generator-electron/issues/19

Upgraded electron to v1 and remove crashReporter

---

.eslintrc
package.json

This change will prevent webpack compatible declarations from erroring. Previously declarations like below would cause an error.
```js
import 'file!./whatever'
```
https://www.npmjs.com/package/eslint-import-resolver-webpack

Add support for webpack-style imports in linter

---

webpack.config.electron.js

This is a fix for an issue I was running into with issue https://github.com/chentsulin/electron-react-boilerplate/issues/232
It adds an `output.libraryTarget` setting into `webpack.config.electron.js` by extending `baseConfig`

extend output config in electron webpack config

---

webpack.config.development.js
webpack.config.production.js

This PR fixes issues with loosing `process.env` object.

Prevent webpack.DefinePlugin to override process.env object

---

main.development.js
package.json

Use `UPGRADE_EXTENSIONS=1 npm run start-hot` to force download extensions.

Add UPGRADE_EXTENSIONS env for devtools-installer

---

package.json
webpack.config.development.js
webpack.config.electron.js
webpack.config.production.js

As discussed in https://github.com/chentsulin/electron-react-boilerplate/issues/264 Using `webpack-merge` simplifies config merging.

use webpack-merge in webpack configs

---

.eslintrc
webpack.config.eslint.js

Eslint webpack import resolver looks for 'webpack.config.js' file as a sibling of the first ancestral package.json. We have no 'webpack.config.js' here so we need to point resolver to some
custom path. Also, we can't point it directly to the 'webpack.config.development.js' file cause it uses ES6 stuff. In order to make eslint import resolver happy the 'webpack.config.eslint.js' is added as a babel-register wrapper around 'webpack.config.development.js'.
Also, invalid json (missing or single quotes) is fixed here as a bonus.

Fix .eslintrc import/resolver settings

---

app/store/configureStore.development.js

The new feature [`Use action creators for Dispatcher`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.4.0) is supported on Redux DevTools Extension@2.4.
Added counter actions & push action of `react-router-redux`.

Add actionCreators option for window.devToolsExtension()

---

.eslintrc

eslint wants it's property keys doublequoted.

Unify/fix .eslintrc quotation

---

.babelrc
package.json

Avoid those babel-plugins swallow console.log in `package.js`. Keeping `no-console` warning by linter should be enough.

Remove remove console, debugger babel-plugin

---

app/index.js
webpack.config.development.js
webpack.config.production.js

This adds the babel-polyfill to the entry of dev and production webpack configs to allow people to use async/await in their app. 
For an example async/await function, add this anywhere in the renderer code:
```
function sleep(ms = 0) {
return new Promise(r => setTimeout(r, ms));
}
async function asyncTest() {
console.log('a');
await sleep(3000);
console.log('b');
}
asyncTest();
```

Enabling use of async/await in renderer

---

README.md

This is a readme-only PR that explains a little more how to use `externals` in the `webpack.config.base.js` file. In retrospect I see how the original documentation explains it, but not at all obvious when I was debugging. Especially with how `ignore` is set up in `package.js`:
```js
ignore: [
'^/test($|/)',
'^/release($|/)',
'^/main.development.js'
].concat(devDeps.map(name => `/node_modules/${name}($|/)`))
.concat(
deps.filter(name => !electronCfg.externals.includes(name))
.map(name => `/node_modules/${name}($|/)`)
)
```
I gave a little more context (the app won't include them during packaging) and what is likely a very common need - installing Bootstrap or some other css framework.
I know it's important to keep the readme a reasonable length for users but I think this is worth it. 
Now …

Adding an externals example using bootstrap in readme

---

package.json
webpack.config.base.js
webpack.config.development.js
webpack.config.electron.js
webpack.config.production.js
webpack.config.test.js

I've found [`webpack-validator`](https://github.com/js-dxtools/webpack-validator) to be very useful in practice when working with webpack, especially with configuration spread across multiple files (even when using `webpack-merge` as this boilerplate is). Besides my own personal experience, I think it would also help beginners with webpack, many of whom may come across this boilerplate looking for something to play around with.

Use webpack-validator.

---

app/store/configureStore.development.js

For [`redux-devtools-extension@2.7.0`](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.7.0), the `window.devtoolsExtension` is ready to deprecated, replaced by `window.__REDUX_DEVTOOLS_EXTENSION__` and `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.

Update redux-devtools-extension use

---

server.js

To #489
1. Add flag option `start-hot`
2. Apply env to `start-hot` mode of server.js, ensure `PORT`, `UPGRADE_EXTENSIONS` can be used for `start-hot`
/cc @amilajack

Add flag option `start-hot` and apply env

---

server.js

We need use `cmd /c "{command}"` for spawn on Windows.
It looks we just left node 4 support, so I just add `shell: true` option. (it only support for node ^6)

Add cross platform support for `start-hot` mode in server.js

---

README.md

First of all, thanks for all your great work! We started to build our electron app based on your boilerplate: https://github.com/Serverless/dashboard
One thing that my team & I struggled with were the purpose of several command e.g. `npm run build` and I opened an issue here: https://github.com/chentsulin/electron-react-boilerplate/issues/532
In order to avoid confusion in the future I propose this addition to the README. As an alternative we could add another directory docs containing a markdown file explaining all the commands and how to use them in combination.

add explanation on npm run build, start and test-e2e

---

.gitattributes

Currently on windows git will checkout the files with CRLF with default settings. The eslint expects the line endings to be LF so this creates EsLint linebreak-style errors. Setting text to end of line to use LF and setting the image files as binaries solved this issue for me.

Set line endings to use LF instead of auto (git)

---

package.json

Added build.files array to prevent the es6 source from being included in the final app distribution as per issue #525.

Prevent inclusion of es6 source in distribution package

---

webpack.config.production.js

Seems that the publicPath was not set correctly. This prevented referenced files (e.g. with the url(...) parameter in less files) to load correctly.

Adapt publicPath in webpack.config.production.js

---

package.json

The build productName is used for the app distributables... suggest to add it here so other people can easily change it without digging through the docs!

add build productName

---

.babelrc

Temporary fix #635.
Add `transform-es2015-classes` / `transform-class-properties` plugins only on development, until https://github.com/gaearon/react-hot-loader/issues/313 fix and we migrated to RHL v3 (#421).
__*NOTE*__ `transform-es2015-classes` is included in `babel-preset-env`, `transform-class-properties` is included in `babel-preset-stage-0`, so we don't need add to `package.json`.

Temporary fix #635, add es2015-classes / class-properties only for dev

---

package.json

babel-plugin-transform-class-properties and babel-plugin-transform-es2015-classes are specified in `.babelrc` but were not in dev dependencies
I assume this works fine with npm@3 and yarn, because they have flat dependency trees. However, these packages should be in dev deps if they are used.
I noticed this when I was checking a really old issue created at pnpm https://github.com/rstacruz/pnpm/issues/79. By the way, I have good news! I worked the last 2 months on a complete rewrite of pnpm and with the latest pnpm@0.48.0, electron-react-boilerplate works with no issues.
This is the only issue, that these 2 deps are not in dev deps

Adding missing dev dependencies

---

app/main.development.js

We should waiting for extensions installation, otherwise content script will not correctly load on renderer process when we use `forceDownload`.
This is fixing recent changes. (from [#651](https://github.com/chentsulin/electron-react-boilerplate/commit/470d082b9e26edc2075d89eac9008ca53a642a65#diff-4fa54749a138460ad8f3583b662fafeaR38))

Fix installExtensions

---

package.json
webpack.config.electron.js
webpack.config.production.js
yarn.lock

v0.0.9 breaks options usage, [see this change](https://github.com/boopathi/babili-webpack-plugin/commit/4dff17d7268849432624d659ae86a7a224859298).
Closes #700.

Fix `babili-wepack-plugin` options for 0.0.9

---

.eslintignore
.eslintrc

It seems have `no-multi-assign` error __only__ on Windows ([AppVeyor build](https://ci.appveyor.com/project/chentsulin/electron-react-boilerplate/build/1384/job/p2svljseu4eoa7l6#L1613)), I don't know why, I've tried on my Windows machine. ¯\\\_(ツ)_/¯
Also add bundle files to eslintignore.

Disable `no-multi-assign` for eslint

---

package.json
webpack.config.electron.js
webpack.config.production.js
yarn.lock

#676 disabled deadcode elimination feature as a temporary fix for #672.
The latest version of `babili-webpack-plugin` will fix it, so we can back.
Closes #718.

Enable deadcode elimination for babili-webpack-plugin v0.0.11

---

.vscode/settings.json
README.md

Added initial vscode support and setup documentation

---

app/main.development.js
app/menu.js

When modifying the code for the menu I thought it would be a good idea to separate it from the main.development.file, add it to a class and break it down to make it easier for people to add changes  and customise menus in the future.

Refactoring code for menu for easier changes

---

webpack.config.electron.js

Currently when production app is running, in the main process just one environment variable exists  - `NODE_ENV`. This change should prevent process.env object from being reset.

Prevent webpack.DefinePlugin from overriding process.env object

---

.vscode/settings.json

If this setting is not present then flow extension suggests to install
flow globally which should is not necessary at all because locally
flow-bin is already available.

Use local flow-bin package

---

app/store/configureStore.development.js

Partially fix #955 
Reloading <kbd>CTRL</kbd>+<kbd>R</kbd> cause the UI not to reload if not on `/` path.

Revert from BrowserHistory to HashHistory

---

webpack.config.renderer.dev.dll.js

Since all webpack configs inherit the base config, and the base config contains `node_modules` in its module resolves, there's no need for this.

Redundant webpack `node_modules` resolve in dev.dll.js

---

test/runTests.js

runTests.js always exits status zero, causing CI not to notice when tests fail.

Make runTests.js exit non-zero when tests fail

---

webpack.config.renderer.dev.js

@jhen0409 @dustintownsend @talha131 @slapbox What do you think about this? I feel like this is what suites most apps. Its also pretty confusing to have `__dirname` and `__filename` [defined differently in production](https://github.com/chentsulin/electron-react-boilerplate/blob/master/webpack.config.main.prod.js#L55-L58). Would love your thoughts on this.

Changed webpack renderer dev node config

---

README.md

There's a problem with npm install and the option to package afterward. With yarn, you don't have this. I know it may be another required technology, but we need to change the doc if we don't fix the problem soon.
(see issue #1065)

Use Yarn instead of npm install

---

test/runTests.js

Pass arguments to jest cli.
With that you can use it for check coverage like `npm test -- --coverage` or update snapshots like `npm test -- --u`.
Closes https://github.com/chentsulin/electron-react-boilerplate/issues/929

Pass arguments to jest cli

---

README.md

"Moved to Multi Platform Build on electron.build site."

Correct Multi Platform Build link in Readme

---

internals/scripts/CheckNativeDep.js
package.json
yarn.lock

Closes #1171 .
Checks if there are any native dependencies not installed inside the `app` folder as they should be ([https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure](url)) on `postinstall`. If there are, a warning is displayed mentioning the issue and a link to the before mentioned page.
By the way, looks like `node-sass` should also be installed inside of `app` by default since it's a native dep.

Check and warn the user if there are native deps installed in root folder

---

webpack.config.renderer.dev.js

Hello,
Thanks for your work! I had a deprecation notice when I tried to run the following command `npm run dev`

Fix deprecation in webpack.config.renderer.dev.js

---

README.md

Added the word "Alternatively" to the run instructions to make it a little clearer that the second set of scripts does the same thing as the first.
Is there some reason a person would want to run those two scripts instead of just `npm run dev`?  Should I add some explanation for why they'd want to do that?

Clarify running instructions

---

package.json
yarn.lock

[Jest](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string) now ships with jsdom.

Remove jsdom dep

---

.babelrc
package.json
yarn.lock

Dynamic imports are supported by webpack. Support was added at [release](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28).

Remove dynamic import dep

---

webpack.config.main.prod.js
webpack.config.renderer.prod.js

`mode: 'production'` is specified in `webpack.config.main.prod.js` and `webpack.config.renderer.prod.js`. That enables `UglifyJSPlugin`. See [default optimization options](https://webpack.js.org/concepts/mode/). Specifying a custom `UglifyJSPlugin` instance in `optimization.minimizer` will [override the default minimizer](https://webpack.js.org/configuration/optimization/#optimization-minimizer).

Move UglifyJSPlugin

---

README.md

Clarifies when to use the `./app/package.json` as mentioned by @ishandutta2007

Clarify the two package.json architecture

---

app/Routes.js
app/components/Counter.js
app/components/Home.js
app/constants/routes.js
app/constants/routes.json
app/containers/Root.js

- rename `routes.js` to `Routes.js` (since it exposes a `React.Component`)
- export const routes from `constants/routes.js`
- use const routes instead of hard coded through the app
resolves #1618

refactor routes to use constants

---

app/store/configureStore.dev.js

- fixed the outdated redux dev tools documents url
+ it moved to http://extension.remotedev.io/docs/API/Arguments.html

fixed the outdated redux dev tools documents url

---

package.json
webpack.config.renderer.prod.js
yarn.lock

Fixes #1646 
`optimize-css-assets-webpack-plugin` was updated to fix a file mapping issue. See the file mapping in devtools below:
`style.css? [sm]:9` isn't ideal.
A number of issues were resolved with `optimize-css-assets-webpack-plugin` in its latest release, however most of those were due to the `css-nano` version it was using, which was updated.

Add production CSS source map

---

README.md

Made any absolute paths in README.md into relative paths, so that ERB can be placed in a subdirectory without having any "image not found" errors.

Change README paths to relative from absolute

---

app/actions/counter.js
app/containers/Root.js
app/reducers/counter.js
app/reducers/types.js

This fixes the errors being raised by `yarn flow`. Error seems to have been introduced when upgrading `flow-bin` in #1664.
I've never used redux before so I may not have defined all the types correctly (possibly got type for state wrong). Please double-check and make any changes as needed.

Fix flow errors caused by "store" prop in Root.js

---

.vscode/settings.json

- Recognize `.eslintignore` `.dockerignore` `.flowconfig` as `ignore` filetypes (since using \# will work as a comment for all of them)
- Recognize `.eslintcache` and `.stylelintrc` as `json` filetypes. (`stylelint` will crash if `.stylelintrc` is a `json` with comments)

VSCode Syntax Highlighting

---

app/reducers/index.js
app/store/configureStore.dev.js
app/store/configureStore.prod.js
test/containers/CounterPage.spec.js

`react-router-redux` was still being used in some areas, switched that for `connected-react-router`.
`routerReducer` is not currently exposed by `connected-react-router`, so I followed a "hack" mentioned [here](https://github.com/supasate/connected-react-router/issues/79#issuecomment-403271755) to add that back.

Fix issues created by adding connected-react-router

---

configs/webpack.config.renderer.dev.js

There was an incorrect path to `app/index.js` which raised an error when running `yarn dev` that the file could not be found.

Fix webpack path for dev

---

internals/scripts/CheckNativeDep.js

Since we've updated the `README` and `package.json` to use `yarn` over `npm`, we should do the same in the `CheckNativeDep` postinstall.
`npm ls` doesn't seem to have a yarn equivalent, but we should figure out a way to replace that since we're not specifying `npm` as a requirement anymore and it's not a dependency.

Specify yarn instead of npm in CheckNativeDep.js

---

package.json

Helps #1689 
`eslint-formatter-pretty` can be used via CLI without specifying its specific location. If `node_modules` was hoisted up, this would raise an error.

Use eslint-formatter-pretty without specifying directory

---

appveyor.yml

It seems `flow-bin` is the reason `appveyor` tests are failing on Windows.
Even `flow-bin`'s Windows tests on `appveyor` have not been passing.
In another repository of mine, the same issue happened on `appveyor` testing with Windows.
I say disable testing `flow` on Windows until we find out more.

Disable flow in appveyor until fixed

---

.stylelintrc
package.json
yarn.lock

stylelint-config-prettier will override clashing rules with any other stylelint configs, to prevent stylelint errors being created due to prettier formatting.

Added stylelint-config-prettier

---

README.md

Since this is a boilerplate, knowing the status of `devDependencies` is also important to users since they'll be working with them.

Add a badge for devDependencies status

---

configs/webpack.config.base.js
configs/webpack.config.renderer.dev.js

In certain cases `path` is being used to create a path to an existing file, which `require.resolve` could also do with less string concatenation (and it may be supported by `eslint-plugin-import` in the future).

Use require.resolve where path is unnecessary

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md
README.md
internals/scripts/CheckNativeDep.js
package.json

Fixes: #1846 
We need to change this old URL
`https://github.com/chentsulin/electron-react-boilerplate` by
`https://github.com/electron-react-boilerplate/electron-react-boilerplate`

Update old url

---

.eslintrc
configs/webpack.config.base.js
configs/webpack.config.renderer.dev.dll.js
internals/scripts/CheckNativeDep.js
internals/scripts/ElectronRebuild.js

some packages have both `package.js` and `package.json` which make json parse throwing error.
like: https://unpkg.com/moment@2.22.2/package.js and https://unpkg.com/moment@2.22.2/package.json

Fix package.json extension missing in webpack config

---

.dockerignore
.eslintignore
.gitignore
.travis.yml

In previous versions of electron-react-boilerplate, there was a
2-package.json structure where modules were installed in
./node_modules and ./app/node_modules. We've since migrated to a
single package.json system, and there should only be ./node_modules
present. If you notice ./app/node_modules (i.e. when running `git
status`), you can safely delete the director ./app/node_modules. All
dependencies are downloaded in ./node_modules now.
History: https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1854

Remove app/node_modules from .gitignore

---

.travis.yml
package.json

Project is not currently working with Node 11. [#1957](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1957#issuecomment-435618180)
Change `devEngines` to `engines` so `yarn` will throw an error if incorrect versions are used.

Fix versions in package.json

---

appveyor.yml

If a dep has been updated in `yarn.lock` but not in `package.json`, the cache should be rebuilt.

Cache node_modules based on yarn.lock

---

package.json

Official install guide shows installing as dev-dependency as well.
Also you presumably wouldn't want to ship a nice tool capable of scrutinizing your ipc messsages, amongst other things, with your production app.

Changed Devtron package to dev-dependency

---

README.md

I kept all the docs that were only essential to getting started with ERB

Remove existing docs and refer to site docs

---

app/index.js
configs/webpack.config.renderer.dev.babel.js

Running `yarn dev` with `PLAIN_HMR=1` (any non-empty string) will disable `react-hot-loader` and rely
solely on existing code that remounts the `Root` component with plain HMR.
This is a quick escape hatch to enable someone to keep working if they encounter an issue like bugs in the code output by `react-hot-loader`'s babel plugin.  Ever since I encountered an issue like that in the past, I decided plain HMR was good enough for me.
fix #2150

add PLAIN_HMR environment variable option

---

app/containers/Root.js
app/index.js
configs/webpack.config.renderer.dev.babel.js
package.json
yarn.lock

- Upgraded semver patch-compliant dependencies
- Upgraded to react-redux@7.1.0 to support React Hooks
- Upgraded dev configs to use React-🔥-Dom. Allows use of React Hooks during RHL and is more resilient to js errors

Dependency upgrades

---

package.json
test/e2e/HomePage.e2e.js
yarn.lock

- Testcafe marked the testcafe-live as obsolete and points to using `--live` flag.
- Minor test names update

Update testcafe live runner and test titles

---

package.json

Hi, I'm proposing adding macOS `package-mac` build option into the package.json
This follows the pre-existing convention where they have specified individual builds for windows / linux.
Personally, I spent ~8mins trying to work out how to build to mac only.
Ended up running `package-linux`, `package-all`, `package`, downloaded 100+ mb of build stuff, then installed `brew install rpm` to get `package-linux` running.
I was wondering what might have prevented a new person from needlessly doing all that when experimenting.
I popped over to https://www.electron.build/configuration/configuration#configuration.
Decided that adding `package-mac` might have been better, so here I am :)

Update package.json mac build option

---

app/menu.ts

Apparently, MenuItemConstructorOptions.selector is a Darwin-only attribute.
TypeScript detects it and displays an error. To fix this error we can cast every menu that is using it to MenuItemConstructorOptions.

Fix TypeScript errors in menu.ts

---

.github/workflows/test.yml
package.json

Reduce verbosity since calling `tsc` directly works just as `yarn ts` would

Remove unnecessary yarn ts script

---

tsconfig.json

Removed `.css` and `.map` files from `tsconfig.json`. They aren't considered anyways during `tsc` execution (according to [typescript documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#details))
> If the "files" and "include" are both left unspecified, the compiler defaults to including all TypeScript (.ts, .d.ts and .tsx) files in the containing directory and subdirectories except those excluded using the "exclude" property. JS files (.js and .jsx) are also included if allowJs is set to true.

Remove unnecessary file extensions from ts exclude

---

.eslintignore

Files that aren't supposed to be linted were being linted. Was causing linting problems in eslint-plugin-compat benchmarks. 
Before and after `yarn lint --debug`:

fix eslint ignore

---

README.md

Current build status badge leads to 404

Badge dead link

---

app/main.dev.ts
configs/webpack.config.renderer.prod.babel.js

**1. App is not showing up**
When I try `yarn build-e2e` and `yarn test-e2e`, app doesn't show up because `app.on('ready')` event is not fired after electron is executed by testcafe. After I use `whenReady()` instead of `on('read')` it works fine.
**2. Webpack Dynamic Imports not working properly**
After electron is launched by testcafe, app can't load `CounterPage` component because script is trying to reference `/app` path instead of `/app/dist/` and showing javascript error below.
```
JavaScript error details:
Error: ENOENT: no such file or directory, open '/User-Directory-Path/electron-react-boilerplate/app/0.renderer.prod.js'
```
However after I build app with `electron-renderer` target not `electron-preload`, dynamic imports works well.
If you know the better way to fix error about …

Fix e2e test error

---

package.json

I believe it makes more sense to have dependency updates in `next` rather than master

Change renovate baseBranch to `next`

---

app/main.dev.ts
package.json

This adds the default app icon to the boilerplate.
Based on https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2511

Provide default app icon

---

package.json
yarn.lock

I tried to use this boilerplate on Windows and it failed. I know cross-env is usually a global, but if it is not on the system already, it is needed.

Missing cross env

---

app/main.dev.ts

It seems that the [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) supports install multiple extensions when passing first argument as array, so there's no need that we do that `promise.all` mapping. Just a tiny improvement which makes it slightly clearer.

chore: improve devtools installer usage

---

.gitattributes

Hi! First of all thanks for your excellent work. Its really saves time. 
I faced with line ending issue with setting from `.gitattributes` - `* text eol=lf`. Point is that when git makes force line endings convertion from CRLF to LF it can break down `.exe` file. It wouldn't work with following output. 
```
Program 'Senso_DK3_connector.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ C:\Users\alex\Projects\frontend-desktop\app\infrastructure\drivers\dk ...
At line:1 char:1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ FullyQualifiedErrorId : NativeCommandFailed
``` 
I suggest makes git handle line endings convertion automatically depending on current system to avoid such issue. 
Thanks.

Makes git automatically converting LF to CRLF and vice versa depending on system

---

src/main.dev.ts

Correct **assets** directory name in _main.dev.ts_ file (previously it was **resources**).

Correct `assets` directory name in main.dev.ts file

---

.erb/scripts/CheckNativeDep.js

If the scan of the **node_modules** reveals no dependencies with binding.gyp files, there is no reason for processing the script further. 
More important, if there are no native dependencies,  line 16 is returning a list of all of the dependencies in the project.
Scripts then fails, reporting incorrect libraries as being native.

Stopping script from processing if there are no native dependencies

---

src/App.global.css

This fixes to small style issues:
1. The cursor style on the buttons is styled incorrectly: it becomes unset when hovering directly over button. 
2. We are able to go to a link when clicking in empty space (because the link span is larger than the button).

fix: incorrect cursor style on button

---

.erb/scripts/CheckBuildsExist.js
src/main.dev.ts

Small fix to some references to the package scripts, which I'm guessing have been renamed at some point possibly

fix: correcting references to names of package scripts

---

README.md

update webpack link from deprecated (https://webpack.github.io/docs/) to modern (https://webpack.js.org/)

change webpack link in README

---

.github/workflows/publish.yml

We use this boilerplate at [ExpressLRS Configurator](https://github.com/ExpressLRS/ExpressLRS-Configurator) and this change improved our build pipeline reliability and reduced built time.
With this change, we cache yarn modules cache dir. During the next builds yarn loads modules from cache first and if it fails it fallbacks to the network.

Save yarn cache dir between builds

---

.erb/configs/webpack.config.eslint.js

I got an unknown module error when executing yarn lint because the require in file webpack.config.eslint.js was referencing a non-existent node_module folder. The error was fixed by not hard-coding the path to the module.

Fix for unknown module eslint config

---

package.json
yarn.lock

Prior to this when running 'yarn package' on an Apple Silicon arm64 chip Electron Builder was defaulting to x64 as opposed to arm64 which was causing errors.
This update of the Electron Builder dependency allows the existing 'yarn package' command to work properly now for those running the new Apple Silicon M1 chips.
Before the update when running 'yarn package' see the error below (on Apple Silicon):
After the update:
I tried modifying the target and passing params to the cli command as well to no avail, so this was the best fix.  Thought I would save the next person struggling to get this to work on if they have the new Mac.

Fixed issue when building an arm64 package on Apple Silicon

---

.erb/configs/webpack.config.base.js

src folder is ../../src relative to this file. 
With the right resolve modules, we can import file use absolute path like "components/File.tsx" instead of "../../components/File.tsx" .

fix: resolve absolute path

---

.erb/configs/webpack.config.renderer.dev.babel.js

The 'yarn build-dll' directive does not exist,simply execute 'yarn '.

feat: update webpack.config.renderer.dev.babel.js

---

src/renderer/App.tsx

A <Router> that keeps the history of your “URL” in memory (does not read or write to the address bar). Environments like React Native use it and I believe this is the right way to do routing with React in Electron.

feat: migrate to memory router

---

.github/ISSUE_TEMPLATE/1-Bug_report.md
README.md

Addresses https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2909
Also updates the README to use the `main` branch instead of `--single-branch' so it matches the instructions in the template, although the end result is the same.

Update README and bug report issue template to recommend correct branch

---

src/main/main.ts

Constant `isDevelopment` wasn't used in `createWindow` function.

Make use of previously created `isDevelopment` constant

---

src/main/main.ts

This prevents the issue where electron throws the `cannot create BrowserWindow` before app is ready exception, when the user clicks the app icon before it is ready.

Fix: enable 'activate' handler only after app is Ready

---

.erb/scripts/link-modules.ts
release/app/package.json

This PR allows to use native modules again. Since the default export is an object, the previous version would use undefined instead of the real paths.

Fix: Paths when importing webpackPaths.

---

.husky/pre-commit
package-lock.json
package.json

Husky did not execute anymore on pre-commit. There seems to have been a breaking change in how husky needs to be configured. 
I have used [typicode/husky-4-to-7](https://github.com/typicode/husky-4-to-7) to convert the existing configuration. Now everything works again as usual.

Fixing husky configuration after moving from husky v4 to husky v7

---

.erb/scripts/notarize.js

env variables are always strings, so doing not on a string only checks that CI has any value, meaning CI=false would not skip notarizing.

Fix: compare env variable to string

---

src/main/main.ts

on('new-window', (event,url)=>...) is deprecated in favor of setWindowOpenHandler.
This fixes a potential future bug if (and when) the new-window event is removed, by moving to setWindowOpenHandler.

fix: use setWindowOpenHandler

---

.github/workflows/publish.yml
.github/workflows/test.yml

Github does not allow secrets to start with `GITHUB_`. 
Changed to `GH_TOKEN` because electron-builder uses that name by default.

fix: rename GITHUB_TOKEN to GH_TOKEN

---

src/main/preload.ts
src/renderer/preload.d.ts

* ChangeLog
* 1. change type 'any' to 'unknown' in 'preload.ts' and 'preload.d.ts'.
* 2. add example 'removeListener' in 'preload.ts' and change 'on' type in 'preload.d.ts' according to 'preload.ts'.
*  - It will be useful example for users to use 'removeListener'.
* close: #3176

feat: replace type 'any' to 'unknown' and more (#3176)

---

.vscode/settings.json

Without this addition VSCode was not picking up on certain TS/React linting errors... Once I added it things worked fine.
([Based on this stackoverflow answer](https://stackoverflow.com/a/55538793/5075148))

feature: Updates  .vscode/settings.json

---

package.json

Start electron like this `electron ./src/main/main.ts` brokes many electron apis:
- `app.getVersion()` - returns version of electron like `18.0.1` instead of `packages.version`
- `app.getPath("userData")` return `%appdata%/Electron` instead of `%appdata%/${package.name}`, i though it was intended behaviour to split up development version from production but looks like its not🙃 just error that appeared long ago 
That behaviour brokes many libraries dependent on `app.getVersion` e.g. in `electron-store` brokes migration feature
Realted issues:
#2397 
#1694 
UPD. I even found [issue in electron repo](https://github.com/electron/electron/issues/14076#issuecomment-447356527) that describes how it works - currently ERB running in not recommended "File mode" while it should run in "Package Mode" …

fix electron broken start

---

src/renderer/App.tsx

As for the [HTML documentation](https://html.spec.whatwg.org/multipage/embedded-content-other.html#attr-dim-width), the `width` attribute of the `img` tag should only contain a non-negative integer value.
> The `width` and `height` attributes... must have values that are [valid non-negative integers](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-non-negative-integer).

fix: Wrong img[width] units in the example app

---

.erb/scripts/clean.js

clean script dont work - "clean.js" only runned in `npm run package` so its not getting any command arguments and `args` always empty
Because its only runned in `npm run package` there is no reason to leave `args` better to keep it simple

fix clean script

---

src/main/util.ts

Is there any reason in returning a function based on env instead of a function that returns a path based on env?
If not I made some refactoring to it.

Refactored resolveHtmlPath

---

.erb/configs/webpack.config.renderer.dev.ts

I noticed that DLLs were being built during the lint script and making things take longer. It's probably not a big deal usually, but when running scripts in CI the dll files don't exist before running eslint and from what I can tell they don't need to be. Figured this might be useful to put up for consideration.
closes https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3290

Skip building DLLs when required from eslint config

---

src/main/preload.ts
src/renderer/preload.d.ts

Fix preload returning ipcRenderer. [Electron's Context Isolation article](https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations) explains that exposing ipcRenderer is unsafe.
- [Security fix] Made `preload.ts`'s `electron.ipcRenderer.on` function stop returning the `IpcRenderer` so that the renderer process cannot freely access the preloader's `ipcRenderer` object.
- Fixed `preload.d.ts`'s type declarations inconsistently using `string` instead of `Channels` as the parameters are defined in `preload.ts`
[Electron's Context Isolation article](https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations) also considers exposing `IpcRenderer.send` to be unsafe. Please consider adding a check to prevent sending messages with …

Fix preload returning ipcRenderer

---

package.json

Fixes  #3326
Add `src` to the `moduleDirectories` Jest option in the root `package.json`, so it's possible to `import hello from 'renderer/hello'` from test files.

fix: allow absolute renderer imports in Jest

---

.erb/configs/webpack.config.main.prod.ts
.erb/configs/webpack.config.renderer.prod.ts

Fixed issue with a used port by the first analyzer when using `ANALYZE=true npm run build`
For clarity, I set both ports (also the default one `8888`).

fix: add ports for build analyzer

---

.erb/configs/webpack.config.main.prod.ts

According to the [documentation](https://www.electronjs.org/docs/latest/api/process#processtype-readonly), the only valid values for `process.type` are:
*  `browser`: The main process.
*  `renderer`: A renderer process.
*  `worker`: In a web worker.
* `utility`: In  a node process launched as a service.
Currently, running the application with `yarn start` the `process.type` value in the main process is `browser`, but in a packaged app it is `main`, so this PR fixes it to be `browser` too.
Consequently, the warning from `electron-devtools-installer` while trying to install `REACT_DEVELOPER_TOOLS` in a production-debug environment is gone.
Fix #3391

fix: set main process.type to "browser" in production

---

.erb/configs/webpack.config.base.ts
package-lock.json
package.json

This PR addresses #3384.
I'm not sure about the `package-lock.json` name changing, but from a quick glance at the commit history, it seems to have changed to this auto-generated one at some point. I assume it's expected?
Also, I added a comment to hint that there's no need for using the `alias` prop now. It seemed a bit cleaner than adding a dummy example path in the `tsconfig`.

Add tsconfig-paths-webpack-plugin to avoid Webpack's alias duplication

---

package.json

Add ignore rule for .erb/dll so that jest doesn't execute all tests twice.

add .erb/dll to jest ignore

---

.eslintrc.js

Related issue: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3468
The root cause is that eslint's rules: `no-shadow` and `no-unused-vars` can't work well with enum in typescript, so replace them with `@typescript-eslint` rules.

fix: custom enum with eslint errors

---

src/main/preload.ts

In electron origin definition with `send` should be allow accept multi args

fix: fix ipcRenderer.sendMessage incorrect defintion

---

.erb/scripts/delete-source-maps.js

Rimraf removed the option to treat file paths as glob patterns, which caused npm run build failing when running the second time.
By adding the option to the rimraf.sync calls, we enable back the behavior we need.

fix: added glob option to rimraf.sync call

---

.erb/scripts/notarize.js

According to the [documentation in electron/notarize](https://github.com/electron/notarize/blob/295c39d8c0ec21efa282161c667576fc7cb39558/README.md?plain=1#L44-L62)
the `appleIdPassword` should be the app-specific-password, and **not** the password of the developer account. 
And, the [electron-builder documentation for macOS signing](https://www.electron.build/configuration/mac) mentions setting the `APPLE_APP_SPECIFIC_PASSWORD` to that value.
**Seeing as this project relies on both these tools, it would be more appropriate to use `APPLE_APP_SPECIFIC_PASSWORD` environment variable rather than `APPLE_ID_PASS` (_which is currently used_)**

fix notarization: use APPLE_APP_SPECIFIC_PASSWORD instead of APPLE_ID_PASS

---

.eslintrc.js

Fix of issue https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3423 and https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3235 by adding the node config to `.eslintrc.js`.

Fixed issue #3423 - updated eslint config for node resolver

---

package.json

Types for the terser-webpack-plugin are no longer needed because they are built-in.

Removed "@types/terser-webpack-plugin"

---

package.json

Fix #3648
I implemented this comment:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3648#issuecomment-2490151716 and now `npm install` runs without error

fix: allow compilation with npm 10.9.0
